sudo: required
services:
  - docker

before_install:
  - docker build -t pradsi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pradsi/react-test npm test

after_success:
  - docker build -t pradsi/multi-client ./client
  - docker build -t pradsi/multi-nginx ./nginx
  - docker build -t pradsi/multi-server ./server
  - docker build -t pradsi/multi-worker ./worker

#push to docker hub
#Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push pradsi/multi-client
  - docker push pradsi/multi-nginx
  - docker push pradsi/multi-server
  - docker push pradsi/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-372866895787
  bucket-path: multi-docker
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY